---
title: "Trends in Graduate Enrollment, Shifting Fields of Study, and Faculty Salary"
author: "Sam Csik"
date: "11/28/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load packages & data}

library(tidyverse)
library(reshape2)

enrollment <- read_csv("grad_enrollment_copy.csv")
postdoc_salary <- read_csv("median_salary_copy.csv")
```


```{r male vs. female grad enrollment (1967-2015)}

# SOURCE: U.S. Department of Education, National Center for Education Statistics, Higher Education General Information Survey (HEGIS), “Fall Enrollment in Colleges and Universities” surveys, 1967 through 1985; Integrated Postsecondary Education Data System (IPEDS),“Fall Enrollment Survey” (IPEDS-EF:86-99); IPEDS Spring 2001 through Spring 2016, Fall Enrollment component. Accessed at: https:// nces.ed.gov/ programs/digest/ d16/ tables/ dt16_303.80.asp.

##############################
# subset total males and females
##############################

total_males <- enrollment %>% 
  select(year, total_males) %>% 
  mutate(total = total_males) # add column called "total" that is equal to the "total_males" column so that we can plot males and females on same plot with same y-axis

total_females <- enrollment %>% 
  select(year, total_females) %>% 
  mutate(total = total_females) # add column called "total" that is equal to the "total_females" column so that we can plot males and females on same plot with same y-axis

##############################
# plot trends through time
##############################

total_enroll_plot <- ggplot(total_males, aes(x = year, y = total)) +
  geom_point(color = "gray30") +
  geom_line(color = "gray30") +
  geom_point(data = total_females, color = "gray30") +
  geom_line(data = total_females, color = "gray30", linetype = "dotted") +
  theme_classic() +
  theme(panel.border = element_rect(colour = "black", fill = NA, size = 0.7)) +
  labs(x = "Year", y = "Total Male & Female Graduate Student \nEnrollment in the U.S.") +
  scale_y_continuous(labels = scales::scientific)

# Figure 1. Male and female graduate enrollment in the U.S. (1967-2015). Male (solid line) and female (dotted line) graduate students...

##############################
# net & percent increase in total males
##############################

m_1967 <- total_males %>% # subset 1967 males
  filter(year == 1967)

m_2015 <- total_males %>% # subset 2015 males
  filter(year == 2015)

net_males <- m_2015$total - m_1967$total # net increase from 1967-2015
perc_males <- ((m_2015$total - m_1967$total)/m_1967$total) * 100 # % increase from 1967 - 2015

##############################
# net & percent increase in total females
##############################

f_1967 <- total_females %>% # subset 1967 females
  filter(year == 1967)

f_2015 <- total_females %>% # subset 2015 females 
  filter(year == 2015)

net_females <- f_2015$total - f_1967$total # net increase from 1967-2015
per_females <- ((f_2015$total - f_1967$total)/f_1967$total) * 100 # % increase from 1967 - 2015

##############################
# stats? can't use t-test b/c you can't compare just 2 values...not sure yet what to use
##############################
```

```{r shifts in female PhD recipients by field (1985, 2000, 2015)}

```

```{r male & female salaries for starting postdoc and other employment positions (2015)}

##############################
# make data into long format
##############################

postdoc_salary_long <- melt(postdoc_salary, variable.name = "employment_status", value.name = "salary") 

##############################
# add column with "sex"
##############################

postdoc_salary_new <- postdoc_salary_long %>%
  mutate(
    sex = case_when(
      employment_status == "employment_males" ~ "Male",
      employment_status == "postdoc_study_males" ~ "Male",
      employment_status == "employment_females" ~ "Female",
      employment_status == "postdoc_study_females" ~ "Female"
    )
  ) %>% 
  mutate(
    status = case_when(
      employment_status == "employment_males" ~ "Employed",
      employment_status == "postdoc_study_males" ~ "Postdoc-study",
      employment_status == "employment_females" ~ "Employed",
      employment_status == "postdoc_study_females" ~ "Postdoc-study"
    )
  )

##############################
# make status a factor, and list levels in the desired facet order
##############################

postdoc_salary_new$status<- factor(postdoc_salary_new$status, levels=c("Postdoc-study", "Employed"))

##############################
# boxplot of employment males vs. females & postdoc males vs. females
##############################

postdoc_salary_plot <- ggplot(postdoc_salary_new, aes(x = sex, y = salary)) +
  geom_boxplot(aes(group = sex, fill = factor(sex))) +
  scale_fill_manual(breaks = c("male", "female"), values = c("white", "darkgrey"), name = "Sex") +
  facet_grid(~ status) +
  labs(x = "Sex", y = "Salary (USD)") +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x=element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=0.7))

```

```{r exploring academic salaries for profs in US colleges}

```

