---
title: "Trends in Graduate Enrollment, Shifting Fields of Study, and Faculty Salary"
author: "Sam Csik, An Bui"
date: "5 December 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Introduction: ** 
-	Women have improved access to post-baccalaureate education  
-	However, there is much gender disparity in discipline-specific involvement and salaries  
-	In the US specifically, faculty salary has increased but female faculty consistently earn less than male faculty (cite table, https://nces.ed.gov/programs/digest/d17/tables/dt17_316.20.asp) 

*Objectives* (we should put this in intro this time):  
  The following report uses publicly available demographic data to evaluate changes in the types of advanced academic degrees sought and by whom, as well as salaries of doctorate degree earners both inside and outside academia and at different stages of their careers. We use these data to assess: 
-	trends in the gender distribution of doctoral students in the US from 1985-2015,   
-	shifts in female enrollment in doctoral programs in the Physical Sciences, Engineering, Education, and the Humanities and Arts in two ways:  
    - how female graduate student research interests have shifted between these four fields, and  
    - how the proportion of female graduate students in these fields have changed  
-	differences in salaries, by sex, after receiving a PhD 
-	variables that may predict faculty salaries.

**Data & Methods:**
  All data were analyzed using R version 3.5.1. We first investigated changes in graduate student enrollment in the United States using data provided by the National Center for Education Statistics (NCES) (cite). We modeled the relationship between year and male and female graduate student enrollment between 1967 and 2015 by fitting linear equations to data on each sex and comparing the rate of change between the two groups.
  Using data provided by the National Scienc Foundatio's (NSF) Survey of Earned Doctorates (cite), we assessed changes in female graduate student research interests across four fields of study--education, engineering, humanities & arts, and the physical & earth sciences--between 1985, 2000, and 2015. A chi-squared test was used to determine whether there was a significant association between year and the type of PhDs awarded to women to evalue a shift in research interests through time. ADD AN'S ANALYSIS HERE. To determine if there are presently (2015) pay disparities between men and women with graduate degrees, we then compared salaries between the sexes in both postdoc and non-postdoc employment positions using a Mann-Whitney U test ($alpha$ = 0.05).
  We lastly constructed a multivariate linear model to describe faculty salary based on X, Y, Z. We later suggest additional parameters that we believe may help to better inform our model.
 
**Analysis & Disucssion**

*Male and female graduate student enrollment in the U.S. (1967-2015)*

  Since 1967, there has been an overall increase in total (part-time, full-time, private, public) graduate student enrollment in the United States (Table 1, Fig. 1). Year is highly correlated with both male (Pearson's *r* = 0.92) and female (Pearson's *r* = 0.99) enrollemnt in graduate programs, though female enrollment has risen at a much faster rate (30,100 students/year) than males (9,096 students/year). As a result, females enrollment in 2015 was 6.5 times greater than in 1967, as compared to the 1.9 fold increase observed for males over the same period of time (Table 1). 
  
*Shifts in female PhD recipients by field (1985, 2000, 2015)*

Comparing total PhD students, there is a significant effect of year on proportion of female students in the physical sciences, (_X_^2^(`r physsci_x2$parameter`) = `r physsci_x2$statistic`, _p_ < 0.001), engineering (_X_^2^(`r eng_x2$parameter`) = `r eng_x2$statistic`, _p_ < 0.001), education (_X_^2^(`r edu_x2$parameter`) = `r edu_x2$statistic`, _p_ < 0.001), and the humanities and arts (_X_^2^(`r arts_x2$parameter`) = `r arts_x2$statistic`, _p_ < 0.001). 

  Further, we found that not only have the proportions of women PhD students (as compared to men) within these focal fields shifted thorugh time, but that the proportion of women completing their degrees within these fields 
 
  ~composition of female phd recipients has changed dramatically thorugh time...~
  
  To determine if the research interests of female PhD students have shifted thorugh time, we assessed PhDs awarded to women across four focal fields of study: education, engineering, humanities & arts, and physical & earth sciences in 1985, 2000, and 2015. We found that field of study differs significantly for female PhD recipients in the years 1985, 2000, 2015 ($\chi^2$(`r female_phd2$parameter`) = `r female_phd2$statistic`, *p* < 0.001). Women were dispropotionately specializing in 

Between 1985 and 2015, female PhD students have shown a growing interest in the physical sciences and engineering, as the percent of female students specializing in the physical sciences has increased 8.6% from 10.1% to 18.7% (cite stacked bar graph) and the percent of female students specializing in engineering has increased 18.2% since 1985. This is reflected in the growing proportion of female students in the total number of students in the physical sciences has doubled between 1985 (0.16) and 2015 (0.34) and quadrupled between 1985 (0.06) and 2015 (0.23) in engineering.




*Salary differences between male and female PhD recipients*

*Modeling faculty salary*

**Conclusion:**
-	Female involvement in higher education has improved, but there are still steps to be made for progress  
    - While the proportion of female doctoral recipients has increased, only 29% of researchers worldwide are women (cite UNESCO, https://www.tellmaps.com/uis/gender/?lang=en#!/tellmap/79054752)
    - Female candidates for jobs are assessed based on whether or not they have children, regardless of the legality of this assessment  
-  While the data we have are as much as we can gather, there are missing components that would be useful for parameterizing a model describing faculty salaries
    - Institution type: research institutions vs liberal arts colleges  
    - Race: women make less than men, but Black women, Asian women, and Hispanic women make less than white women (there are numbers, will find later)  
-	Race is a particularly egregious variable to be left out, especially since it stratifies so much of higher education  
    - 64% of Bachelor’s degrees conferred are to white students (cite table, https://nces.ed.gov/programs/digest/d17/tables/dt17_322.20.asp)  
    -	66% of PhD recipients are white (cite table, https://nces.ed.gov/programs/digest/d17/tables/dt17_324.20.asp)  
    -	82% of professors are white (55% men, 27% women, cite figure, https://nces.ed.gov/fastfacts/display.asp?id=61)  
