---
title: "Faculty Salary Model"
author: "Sam Csik"
date: "12/4/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(reshape2) 
library(effsize)
library(scales)
library(extrafont)
library(car)
library(stargazer)
library(wesanderson)

enrollment <- read_csv("grad_enrollment_copy.csv")
postdoc_salary <- read_csv("median_salary_copy.csv")
fields <- read_csv("phds_by_field_copy.csv")
faculty_salary <- read_csv("faculty_salary.csv")
phd_fields_field <- read_csv("phds_field_field.csv")
```

*Modeling faculty salary*

```{r visualize faculty_salary data}
##############################
# Look at data
##############################

fac_by_dept_plot <- ggplot(data = faculty_salary, aes(x = years_service, y = salary)) +
  geom_point(aes(color = rank, pch = sex)) +
  facet_wrap(~ discipline)
# too much variability to determine a stat. sig effect between sexes? see models below

##############################
# Explore relationships between variables that could be correlated
##############################

# looking for colinearity between years_since and years_service
years_plot <- ggplot(faculty_salary, aes(x = years_since, y = years_service)) +
  geom_point()
# FINDINGS: appear to be correlated (i.e. increase in years_since = ~ linear increase in years_service)
```

```{r multivariate linear regression for faculty salary}
# run full model then find VIF to look for colinearity
full_lm1 <- lm(salary ~ rank + discipline + years_since + years_service + sex, data = faculty_salary)
summary(full_lm1) # R2 = 0.44, p < 0.002
plot(full_lm1) # does NOT look good. Heteroscedastic??
vif(full_lm1)
# FINDINGS: years_since & years_service both have VIF > 4 (some correlation, think critically about possible overlaps); this in combination with "years_plot" make me think that we should drop one of these predictor variables--I'm inclined to keep years_service because I think it makes more sense that the longer that you've been faculty, the higher your rank (see fac_by_dept_plot)--which typically means the higher your salary

# lm 2 includes rank, discipline, sex, years_serive (eliminated years_since becuase it appeared correlated with years_service)
facsal_lm2 <- lm(salary ~ rank + discipline + years_service + sex, data = faculty_salary)
summary(facsal_lm2) # R2 = 0.44, p < 0.001 # reference = female, A, Associate Prof
plot(facsal_lm2) # don't look any better than lm1
vif(facsal_lm2) # no correlataion between variables GOOD!
# FINDINGS: not necessarily non-linear (residuals vs fitted); appears to be heteroscedastic (Scale-Location plot)

# lm3 includes discipline, sex, years_service (eliminated rank because rank and years_service should be correlated and may be competing to explain variation...hence why years_service is not sig in lm2)
facsal_lm3 <- lm(salary ~ discipline + years_service + sex, data = faculty_salary)
summary(facsal_lm3) # R2 = 0.16...NOT GOOD, p < 0.001 # reference = female, A
plot(facsal_lm3) # these look A LOT BETTER than lm1, lm2!!! no heteroscedasticity
vif(facsal_lm3) # no correlation
```

```{r AIC values}
#### all disciplines ####
AIC_full_lm1 <- AIC(full_lm1)
AIC_full_lm1
# 9093.826

AIC_lm2 <- AIC(facsal_lm2) # difference of 2 in AIC may be considered not different...this is pretty close to lm1 so I'd be inclined to keep this over the full model
AIC_lm2
# 9096.813

AIC_lm3 <- AIC(facsal_lm3) # WELL FUCK. definitely not good, thought i may have been on to something...
AIC_lm3
# 9257.162
```

```{r make table using stargazer}
stargazer(full_lm1, facsal_lm2, type = "html")
```

